# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170711_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted', '-last_updated']},
        ),
    ]
