# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 13, 9, 59, 17, 545561, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
